before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive-full

script:
  - make all
  - mkdir public
  - mv GettingStartedWithLedger.* public/
  - mv public/GettingStartedWithLedger.html public/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  name: $GITHUB_USERNAME
  email: $GITHUB_EMAIL
  local_dir: public
  on:
    branch: traduction_fr